<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/pandas_null_check.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://github.com/erkansirin78/datasets/raw/refs/heads/master/OnlineRetail2.csv ##adreste rawa sağ tıklayıp bu
#adresi aldım copy link adress olacak

In [1]:
! wget https://github.com/erkansirin78/datasets/raw/refs/heads/master/OnlineRetail2.csv

--2026-03-20 18:26:57--  https://github.com/erkansirin78/datasets/raw/refs/heads/master/OnlineRetail2.csv
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/OnlineRetail2.csv [following]
--2026-03-20 18:26:57--  https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/OnlineRetail2.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48039726 (46M) [text/plain]
Saving to: ‘OnlineRetail2.csv’

OnlineRetail2.csv   100%[===================>]  45.81M   211MB/s    in 0.2s

2026-03-20 18:26:58 (211 MB/s) - ‘OnlineRetail2.csv’ saved [48039726/48039726]

In [2]:
import pandas as pd

In [11]:
df = pd. read_csv("OnlineRetail2.csv")

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [13]:
#Customer Id yi float yerine strşng yapmak istiyorum
df['CustomerID'] = df['CustomerID'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   541909 non-null  object
 7   Country      541909 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 33.1+ MB

In [8]:
#dataframe null kontrolü
df.isnull().values.any()

np.True_

In [9]:
df.isnull().values.sum()

np.int64(1454)

In [14]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64

In [15]:
#null değerleri düşürme
df2 = df.dropna()

In [17]:
df2.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [18]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64

In [20]:
#sütun ve satırları Indeks Numaraları ile Seçmek
df.iloc[:,[2,5,7]].head()

                           Description  UnitPrice         Country
0   WHITE HANGING HEART T-LIGHT HOLDER       2.55  United Kingdom
1                  WHITE METAL LANTERN       3.39  United Kingdom
2       CREAM CUPID HEARTS COAT HANGER       2.75  United Kingdom
3  KNITTED UNION FLAG HOT WATER BOTTLE       3.39  United Kingdom
4       RED WOOLLY HOTTIE WHITE HEART.       3.39  United Kingdom

In [22]:
df.iloc[16:20,:].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom

In [23]:
df.iloc[0:5,0:5]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00