<a href="https://colab.research.google.com/github/saimeonver/Pandas_dataengineer_notes/blob/main/09_pandas_join_union.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
! wget https://github.com/erkansirin78/datasets/raw/refs/heads/master/retail_db/order_items.csv

--2026-03-21 15:03:50--  https://github.com/erkansirin78/datasets/raw/refs/heads/master/retail_db/order_items.csv
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/retail_db/order_items.csv [following]
--2026-03-21 15:03:51--  https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/retail_db/order_items.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5408988 (5.2M) [text/plain]
Saving to: ‘order_items.csv’

order_items.csv     100%[===================>]   5.16M  --.-KB/s    in 0.08s

2026-03-21 15:03:51 (66.6 MB/s) - ‘order_items.csv’ saved [5408988/5408988]

In [3]:
! wget https://github.com/erkansirin78/datasets/raw/refs/heads/master/retail_db/products.csv

--2026-03-21 15:04:47--  https://github.com/erkansirin78/datasets/raw/refs/heads/master/retail_db/products.csv
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/retail_db/products.csv [following]
--2026-03-21 15:04:47--  https://raw.githubusercontent.com/erkansirin78/datasets/refs/heads/master/retail_db/products.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 174196 (170K) [text/plain]
Saving to: ‘products.csv’

products.csv        100%[===================>] 170.11K  --.-KB/s    in 0.03s

2026-03-21 15:04:48 (6.33 MB/s) - ‘products.csv’ saved [174196/174196]

In [15]:
order_items = pd.read_csv('order_items.csv')

In [16]:
products = pd.read_csv("products.csv")

Let's first inspect rows in the `outer_join` where data from `order_items` is missing, indicating they originated only from the `products` table and had no corresponding `orderItemProductId` in `order_items`.

In [ ]:
missing_order_items_data = outer_join[outer_join['orderItemName'].isna()]
display(missing_order_items_data.head())

Now, let's inspect rows in the `outer_join` where data from `products` is missing, indicating they originated only from the `order_items` table and had no corresponding `productId` in `products`.

In [ ]:
missing_products_data = outer_join[outer_join['productName'].isna()]
display(missing_products_data.head())

In [6]:
order_items.head()

,orderItemName,orderItemOrderId,orderItemProductId,orderItemQuantity,orderItemSubTotal,orderItemProductPrice
0,1,1,957,1,299.98,299.98
1,2,2,1073,1,199.99,199.99
2,3,2,502,5,250.00,50.00
3,4,2,403,1,129.99,129.99
4,5,4,897,2,49.98,24.99

In [7]:
products.head()

,productId,productCategoryId,productName,productDescription,productPrice,productImage
0,1,2,Quest Q64 10 FT. x 10 FT. Slant Leg Instant U,NaN,59.98,http://images.acmesports.sports/Quest+Q64+10+F...
1,2,2,Under Armour Men's Highlight MC Football Clea,NaN,129.99,http://images.acmesports.sports/Under+Armour+M...
2,3,2,Under Armour Men's Renegade D Mid Football Cl,NaN,89.99,http://images.acmesports.sports/Under+Armour+M...
3,4,2,Under Armour Men's Renegade D Mid Football Cl,NaN,89.99,http://images.acmesports.sports/Under+Armour+M...
4,5,2,Riddell Youth Revolution Speed Custom Footbal,NaN,199.99,http://images.acmesports.sports/Riddell+Youth+...

In [8]:
#Union two dataframe with concatenate
products.shape

(1345, 6)

In [9]:
union_products = pd.concat([products, products])
union_products.shape

(2690, 6)

In [10]:
#inner join two dataframe with merge
inner_join = pd.merge(order_items,products, left_on="orderItemProductId", right_on ="productId")
inner_join.head()

,orderItemName,orderItemOrderId,orderItemProductId,orderItemQuantity,orderItemSubTotal,orderItemProductPrice,productId,productCategoryId,productName,productDescription,productPrice,productImage
0,1,1,957,1,299.98,299.98,957,43,Diamondback Women's Serene Classic Comfort Bi,NaN,299.98,http://images.acmesports.sports/Diamondback+Wo...
1,2,2,1073,1,199.99,199.99,1073,48,Pelican Sunstream 100 Kayak,NaN,199.99,http://images.acmesports.sports/Pelican+Sunstr...
2,3,2,502,5,250.00,50.00,502,24,Nike Men's Dri-FIT Victory Golf Polo,NaN,50.00,http://images.acmesports.sports/Nike+Men%27s+D...
3,4,2,403,1,129.99,129.99,403,18,Nike Men's CJ Elite 2 TD Football Cleat,NaN,129.99,http://images.acmesports.sports/Nike+Men%27s+C...
4,5,4,897,2,49.98,24.99,897,40,Team Golf New England Patriots Putter Grip,NaN,24.99,http://images.acmesports.sports/Team+Golf+New+...

In [17]:
#outer join two dataframes
outer_join = pd.merge(order_items,products,left_on = "orderItemProductId", right_on = "productId", how="outer")

In [19]:
outer_join.head(50)

,orderItemName,orderItemOrderId,orderItemProductId,orderItemQuantity,orderItemSubTotal,orderItemProductPrice,productId,productCategoryId,productName,productDescription,productPrice,productImage
0,NaN,NaN,NaN,NaN,NaN,NaN,1,2,Quest Q64 10 FT. x 10 FT. Slant Leg Instant U,NaN,59.98,http://images.acmesports.sports/Quest+Q64+10+F...
1,NaN,NaN,NaN,NaN,NaN,NaN,2,2,Under Armour Men's Highlight MC Football Clea,NaN,129.99,http://images.acmesports.sports/Under+Armour+M...
2,NaN,NaN,NaN,NaN,NaN,NaN,3,2,Under Armour Men's Renegade D Mid Football Cl,NaN,89.99,http://images.acmesports.sports/Under+Armour+M...
3,NaN,NaN,NaN,NaN,NaN,NaN,4,2,Under Armour Men's Renegade D Mid Football Cl,NaN,89.99,http://images.acmesports.sports/Under+Armour+M...
4,NaN,NaN,NaN,NaN,NaN,NaN,5,2,Riddell Youth Revolution Speed Custom Footbal,NaN,199.99,http://images.acmesports.sports/Riddell+Youth+...
5,NaN,NaN,NaN,NaN,NaN,NaN,6,2,Jordan Men's VI Retro TD Football Cleat,NaN,134.99,http://images.acmesports.sports/Jordan+Men%27s...
6,NaN,NaN,NaN,NaN,NaN,NaN,7,2,Schutt Youth Recruit Hybrid Custom Football H,NaN,99.99,http://images.acmesports.sports/Schutt+Youth+R...
7,NaN,NaN,NaN,NaN,NaN,NaN,8,2,Nike Men's Vapor Carbon Elite TD Football Cle,NaN,129.99,http://images.acmesports.sports/Nike+Men%27s+V...
8,NaN,NaN,NaN,NaN,NaN,NaN,9,2,Nike Adult Vapor Jet 3.0 Receiver Gloves,NaN,50.00,http://images.acmesports.sports/Nike+Adult+Vap...
9,NaN,NaN,NaN,NaN,NaN,NaN,10,2,Under Armour Men's Highlight MC Football Clea,NaN,129.99,http://images.acmesports.sports/Under+Armour+M...
10,NaN,NaN,NaN,NaN,NaN,NaN,11,2,Fitness Gear 300 lb Olympic Weight Set,NaN,209.99,http://images.acmesports.sports/Fitness+Gear+3...
11,NaN,NaN,NaN,NaN,NaN,NaN,12,2,Under Armour Men's Highlight MC Alter Ego Fla,NaN,139.99,http://images.acmesports.sports/Under+Armour+M...
12,NaN,NaN,NaN,NaN,NaN,NaN,13,2,Under Armour Men's Renegade D Mid Football Cl,NaN,89.99,http://images.acmesports.sports/Under+Armour+M...
13,NaN,NaN,NaN,NaN,NaN,NaN,14,2,Quik Shade Summit SX170 10 FT. x 10 FT. Canop,NaN,199.99,http://images.acmesports.sports/Quik+Shade+Sum...
14,NaN,NaN,NaN,NaN,NaN,NaN,15,2,Under Armour Kids' Highlight RM Alter Ego Sup,NaN,59.99,http://images.acmesports.sports/Under+Armour+K...
15,NaN,NaN,NaN,NaN,NaN,NaN,16,2,Riddell Youth 360 Custom Football Helmet,NaN,299.99,http://images.acmesports.sports/Riddell+Youth+...
16,NaN,NaN,NaN,NaN,NaN,NaN,17,2,Under Armour Men's Highlight MC Football Clea,NaN,129.99,http://images.acmesports.sports/Under+Armour+M...
17,NaN,NaN,NaN,NaN,NaN,NaN,18,2,Reebok Men's Full Zip Training Jacket,NaN,29.97,http://images.acmesports.sports/Reebok+Men%27s...
18,144776.0,57864.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
19,145164.0,58018.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
20,146401.0,58491.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
21,146472.0,58522.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
22,146941.0,58707.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
23,148259.0,59238.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
24,148666.0,59384.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
25,149085.0,59565.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
26,149189.0,59610.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
27,149652.0,59791.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
28,149741.0,59826.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
29,149773.0,59839.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
30,149965.0,59915.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
31,150091.0,59971.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
32,150622.0,60201.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
33,151336.0,60473.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
34,151489.0,60524.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
35,151756.0,60629.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
36,151989.0,60731.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
37,152235.0,60839.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
38,153127.0,61216.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
39,153158.0,61234.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
40,154659.0,61871.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
41,155186.0,62067.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
42,155522.0,62203.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
43,155776.0,62310.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
44,156117.0,62462.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
45,156149.0,62475.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
46,156184.0,62492.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
47,156218.0,62508.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
48,156388.0,62569.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...
49,157083.0,62825.0,19.0,1.0,124.99,124.99,19,2,Nike Men's Fingertrap Max Training Shoe,NaN,124.99,http://images.acmesports.sports/Nike+Men%27s+F...